title: "Misagh Kordi"
email: "misaghkordi1987@gmial.com"
description: >-
  Personal website showcasing projects, references, and resources on AI, LLMs, and bioinformatics.
baseurl: ""
url: "https://kordimisagh.github.io"

# Theme settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

# Optional settings
author:
  name: "Zahra Fayaziboroujeni"
  avatar: "/assets/images/profile.jpg"

show_excerpts: true
paginate: 5
