title: "Misagh Kordi"
email: "misaghkordi1987@gmail.com"
description: >-
  Personal website showcasing projects, references, and resources on AI, LLMs, and bioinformatics.
baseurl: ""
url: "https://kordimisagh.github.io"

# Theme settings
remote_theme: "mmistakes/minimal-mistakes"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-remote-theme

# Author
author:
  name: "Misagh Kordi"
  avatar: "/assets/images/IMG_3932.jpg"
  bio: "Researcher in AI, LLMs, and Bioinformatics"
  location: "California, USA"
  email: "misaghkordi1987@gmail.com"
  github: kordimisagh
  linkedin: https://www.linkedin.com/in/misagh-kordi-752448109/


header_pages:
  - index.md
  - about.md
  - posts.md
  - tags.md
  - archive.md
  - project.md

# Features
show_excerpts: true
search: true

# Archives for Tags
collections:
  tags:
    output: true
    permalink: /tags/:path/

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag
  permalinks:
    tag: '/tags/:name/'

# Pagination
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Header Image
header:
  overlay_image: /assets/images/IMG_4965.jpg
  overlay_filter: 0.5
  caption: "Exploring AI and Bioinformatics"

# Google Analytics (optional)
google_analytics: UA-XXXXXX-Y
